### ISSUE TITLE
Basic Misunderstanding

### ISSUE THREAD

**Issue by xpde** [NeotiDev/matrix#1]
When you create a single document project (such as this one), it is recommended that you create a [Gist](https://gist.github.com/) rather than an entire repository.

**Comment by PCTipsGR** [comment]
I am not sure if gists allow you to make releases. 
Anyway, I have assigned the owner and script creator here so that he can check and decide.

**Comment by PCTipsGR** [comment]
@xpde I am also almost certain that organisations cannot create gists.

**Comment by yagizhan49** [comment]
I think we can’t make releases in Gists. So this way works better. Users can also make pull requests if we work on a repository too. And i’m thinking to merge these mini-repos and make a full toolbox. But now, we’ll work on repositories.

**Comment by PCTipsGR** [comment]
Yep, I agree. And since gists cannot be developed, thread closed.

Adding a full batch toolbox would be nice, however.

**Comment by xpde** [comment]
Gist can not be created by an organizations for many reasons. Also, Gist can most certainly be developed. You can easily modify a Gist as well as become a stargazer for one (Star). I am just stating that if you guys are to create a single file project, gist is recommended due to the fact that creating an entire repository for a single file is just too much effort if nothing is being commited to the repo besides that one file.
